# Generated by Django 5.0.6 on 2024-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandassault',
            name='color',
            field=models.CharField(choices=[('Red', 'Explosive'), ('Yellow', 'Piercing'), ('Blue', 'Mystic'), ('Purple', 'Sonic'), ('Normal', 'Normal')], default='Normal', max_length=20),
        ),
    ]
