# Generated by Django 5.0.6 on 2024-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grand_assaults',
            field=models.ManyToManyField(blank=True, related_name='students_grand_assault', to='myapp.grandassault'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_assaults',
            field=models.ManyToManyField(blank=True, related_name='students_total_assault', to='myapp.totalassault'),
        ),
    ]
